# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload.proto',
  package='playground',
  syntax='proto3',
  serialized_pb=_b('\n\rpayload.proto\x12\nplayground\"%\n\x07Payload\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x32\x81\x01\n\x0eProcessPayload\x12\x35\n\x07process\x12\x13.playground.Payload\x1a\x13.playground.Payload\"\x00\x12\x38\n\x06stream\x12\x13.playground.Payload\x1a\x13.playground.Payload\"\x00(\x01\x30\x01\x62\x06proto3')
)




_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='playground.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='playground.Payload.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='playground.Payload.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'payload_pb2'
  # @@protoc_insertion_point(class_scope:playground.Payload)
  ))
_sym_db.RegisterMessage(Payload)



_PROCESSPAYLOAD = _descriptor.ServiceDescriptor(
  name='ProcessPayload',
  full_name='playground.ProcessPayload',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=69,
  serialized_end=198,
  methods=[
  _descriptor.MethodDescriptor(
    name='process',
    full_name='playground.ProcessPayload.process',
    index=0,
    containing_service=None,
    input_type=_PAYLOAD,
    output_type=_PAYLOAD,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stream',
    full_name='playground.ProcessPayload.stream',
    index=1,
    containing_service=None,
    input_type=_PAYLOAD,
    output_type=_PAYLOAD,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROCESSPAYLOAD)

DESCRIPTOR.services_by_name['ProcessPayload'] = _PROCESSPAYLOAD

# @@protoc_insertion_point(module_scope)
