# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import payload_pb2 as payload__pb2


class ProcessPayloadStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.process = channel.unary_unary(
        '/playground.ProcessPayload/process',
        request_serializer=payload__pb2.Payload.SerializeToString,
        response_deserializer=payload__pb2.Payload.FromString,
        )
    self.stream = channel.stream_stream(
        '/playground.ProcessPayload/stream',
        request_serializer=payload__pb2.Payload.SerializeToString,
        response_deserializer=payload__pb2.Payload.FromString,
        )


class ProcessPayloadServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def process(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProcessPayloadServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'process': grpc.unary_unary_rpc_method_handler(
          servicer.process,
          request_deserializer=payload__pb2.Payload.FromString,
          response_serializer=payload__pb2.Payload.SerializeToString,
      ),
      'stream': grpc.stream_stream_rpc_method_handler(
          servicer.stream,
          request_deserializer=payload__pb2.Payload.FromString,
          response_serializer=payload__pb2.Payload.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'playground.ProcessPayload', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
